### ISSUE TITLE
youtube_playlist_reverse.js Stopped WorkingGree

### ISSUE THREAD

**Issue by JFuller69** [Dragosarus/Userscripts#1] opened 2021-08-27 14:46 UTC
Greetings, 
Been using this pretty much sense it's inception, & last several months Flawlessly.. As of yesterday, it completely stopped working.. Problems started last week where after many "clearing cache/deleting cookies/F5's/etc" could eventually get script to "catch".. but had to repeatedly do that for EACH applicable Tab.. But as of now, nothing works anymore.. Script seems to be running, button displays, can tweak script button's "inital state" to "false/true/false" & F5 = button responds.. Added 3 seconds to Both "redirectWhenTimeLeft" = No Help.. Using Firefox , tested on versions old to recent = No Help.. No other changes to my system during this time, etc etc etc..
 
Has YouTube changed something, etc etc? Any other recent known issues / thoughts?.. Please Advise..
Thanks.

**Comment by Dragosarus** [comment] 2021-08-27 18:10
Thanks for reporting this; I've added an update (c38ce77ff597e8027e04aeca7ca6031dcd025543) that should fix the issue.

YouTube has recently been changing parts of their UI -- the location of the video description, icons etc. This includes the design of the shuffle button, which meant the script could no longer find it (in order to avoid overriding the shuffle function if it's enabled).

I assume that YT's A/B testing is what caused the new UI to be displayed (and the old one to reappear after clearing cache/cookies etc.), but let me know if this assumption is wrong and the new update has not fixed things fully.

**Comment by JFuller69** [comment] 2021-10-25 20:48
Thanks Again for Responding/Fixing that last issue so Quickly!.. We left you a “Rave Review” for it 😊..

 

Got an apparent new issue..

 

For approx. 2 weeks now, when the YT playlist finishes the “last/#1” video, the processor spikes / Browser Locks Up / RAM will swell to “many GBs” until the Browser Crashes..

 

During that process, sometimes a “Warning Msg” appears, or if “left clicking” “away from video frame” on YT page, same msg pops up, ie- “GreaseMonkey is slowing this page.. Click to Stop It” etc etc..

 

Stopping GreaseMonkey ends the siege / browser unfreezes etc.. Sometimes RAM will drop to normal, sometimes have to duplicate tab & close the old tab for RAM to reset..

 

Anywho, our observation is “something YT has changed” & it’s Battling the Reverse Order script to Play video #2 / “the regular order of Newest to Oldest” etc..

 

Sometimes when GreaseMonkey is force stopped, the list will remain calmly at #1.. other times, YT takes over & starts playing video #2..

 

If the #1 video is Paused before hitting “the end of video”.. the tab will remain calm / no problems..

 

We have tested & duplicated on FF52esr , 54 , 73 , & 91.. all equal same results..

 

We first tested using script v7.1 ..and then install / tested with v7.4 ..both equaled the same problem across all noted browser version..

 

So, can you duplicate?.. any ideas/thoughts?...

 

Thanks Again.

**Comment by Dragosarus** [comment] 2021-10-26 04:28
Thanks again for reporting this. I believe you are correct in that the issue is caused by a YT change: it appears to be the same issue described in 445f9748b1edf10ad8d04c87d9d99ffac6a454f5 for a different script. A fix has been applied (d41afd5c0ab38ec22150aa28f7e7e66921e1fc65) and the script should now function properly.

Looking into it, it appears that YT now stores the playlist sidebar used with the miniplayer _before_ the user enables it (if I recall correctly, this used to be loaded when needed). Notably, this sidebar is initally empty and is not updated until the user enters miniplayer mode; this caused `getVidNum()` to output `[NAN, NAN]` which tricked the script into believing the first video in the playlist had not yet been reached (and as a result got stuck in an infinite loop).

**Comment by tubedogg** [comment] 2021-10-27 10:01
Thank you for this awesome script. It's made watching upload playlists massively easier.

That said, I ran into an issue today where it stopped working out of nowhere. There was an error in the console about TrustedHTML. Script injection through TamperMonkey was having a problem. TamperMonkey has released an update to their Beta extension that resolves that issue. But once I got up and running in TM beta, the error in the console went away and it was still silently failing.

After a little superficial debugging, it seems that if the playlist contains over 999 videos, the numbers that `getVidNum()` is looking at now contain commas, which is tripping up `parseInt()`, causing `getVidNum()` to return only the digit(s) before the comma--1, in my case, which meant it wasn't redirecting at all. If the number had been a 2, at least it would have redirected to the second video in the playlist every time and I could have been sure it was at least doing _something_.

I say "now" because I am playing the same playlist I was playing last week with more than 1,600 videos on it, and it worked just fine last week. The line I had to change to get it working again hasn't substantively changed in quite a while in your repository.

I fixed it by doing this, although I'm sure there is a more elegant solution:

                return vidNum.split(" / ").map(x => parseInt(x));

becomes

                return vidNum.replace(',', '').split(" / ").map(x => parseInt(x));


I'm not sure if you want this here or if you'd prefer a separate issue for it but I figured it seemed related.

**Comment by Dragosarus** [comment] 2021-10-27 12:39
Adding it here is completely fine!

I was not aware of this `parseInt()` behaviour, so thanks for letting me know. Since `getVidNum()` is only used to check if the current video is the first in the playlist I have opted to directly use the result of `vidNum.split(" / ")` instead. The script should now work for videos with index 999 < x < 2000.

**Closed as completed** 2021-10-28 12:54 UTC

**Comment by JFuller69** [comment] 2021-11-01 14:28
Follow-Up Findings.. Been testing last several days, and the script is working Flawlessly once again.. Great Job 👍 / Thanks Again 🤗 !
